minor_changes:
- terraform - Adds option ``variables_files`` for multiple var-files (https://github.com/ansible-collections/community.general/issues/224).
- terraform - Adds option ``backend_config_files``. This can accept a list of paths to multiple configuration files.